# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devbox < Formula
  desc ""
  homepage ""
  version "0.1.17"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pilat/devbox/releases/download/v0.1.17/devbox_0.1.17_Darwin_x86_64.tar.gz"
      sha256 "41ef34367914bcb5aa487540cd70c8fa3bc016bb74ccc2433518ad73683cc8ba"

      def install
        bin.install "devbox"
        bash_completion.install "completions/devbox.bash" => "devbox"
        zsh_completion.install "completions/devbox.zsh" => "_devbox"
        fish_completion.install "completions/devbox.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pilat/devbox/releases/download/v0.1.17/devbox_0.1.17_Darwin_arm64.tar.gz"
      sha256 "3c734aab103941f7f72abb4bde57de2f3be3130b0e2fc6b46330e42d2dcfa31b"

      def install
        bin.install "devbox"
        bash_completion.install "completions/devbox.bash" => "devbox"
        zsh_completion.install "completions/devbox.zsh" => "_devbox"
        fish_completion.install "completions/devbox.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pilat/devbox/releases/download/v0.1.17/devbox_0.1.17_Linux_x86_64.tar.gz"
        sha256 "0d85494c7adcdd8c46818fda053c14fb989a2934f679ed9d58d8d51da1e39ddf"

        def install
          bin.install "devbox"
          bash_completion.install "completions/devbox.bash" => "devbox"
          zsh_completion.install "completions/devbox.zsh" => "_devbox"
          fish_completion.install "completions/devbox.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pilat/devbox/releases/download/v0.1.17/devbox_0.1.17_Linux_arm64.tar.gz"
        sha256 "09ee5d3af847a2bb228d4f8184f1933527fbf01d08ca43f5237ba4350dfd89f5"

        def install
          bin.install "devbox"
          bash_completion.install "completions/devbox.bash" => "devbox"
          zsh_completion.install "completions/devbox.zsh" => "_devbox"
          fish_completion.install "completions/devbox.fish"
        end
      end
    end
  end
end
