# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devbox < Formula
  desc ""
  homepage ""
  version "0.1.11"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pilat/devbox/releases/download/v0.1.11/devbox_0.1.11_Darwin_x86_64.tar.gz"
      sha256 "fe04b16be8d90e9525ea80082802136b3352712cff91c6fad704a05bbe31d5e1"

      def install
        bin.install "devbox"
        bash_completion.install "completions/devbox.bash" => "devbox"
        zsh_completion.install "completions/devbox.zsh" => "_devbox"
        fish_completion.install "completions/devbox.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pilat/devbox/releases/download/v0.1.11/devbox_0.1.11_Darwin_arm64.tar.gz"
      sha256 "cd4d152e23d2228939e0af7068db747da7c4fab5b88b7598d2da49802d9f0aa2"

      def install
        bin.install "devbox"
        bash_completion.install "completions/devbox.bash" => "devbox"
        zsh_completion.install "completions/devbox.zsh" => "_devbox"
        fish_completion.install "completions/devbox.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pilat/devbox/releases/download/v0.1.11/devbox_0.1.11_Linux_x86_64.tar.gz"
        sha256 "7ce7b7b1731e7fe60521313d34b56337100c5edd45b06904b066b71f0e10875a"

        def install
          bin.install "devbox"
          bash_completion.install "completions/devbox.bash" => "devbox"
          zsh_completion.install "completions/devbox.zsh" => "_devbox"
          fish_completion.install "completions/devbox.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pilat/devbox/releases/download/v0.1.11/devbox_0.1.11_Linux_arm64.tar.gz"
        sha256 "03c95b44dca9abacf66f68f542819850e8b9105234a9a2c07c06544c5c06ad19"

        def install
          bin.install "devbox"
          bash_completion.install "completions/devbox.bash" => "devbox"
          zsh_completion.install "completions/devbox.zsh" => "_devbox"
          fish_completion.install "completions/devbox.fish"
        end
      end
    end
  end
end
