# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devbox < Formula
  desc ""
  homepage ""
  version "0.1.9"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pilat/devbox/releases/download/v0.1.9/devbox_0.1.9_Darwin_x86_64.tar.gz"
      sha256 "53baa5c86cfcb4195bdadcdc82a37a312a970dcfbe7da79250d1674d24dd4c9a"

      def install
        bin.install "devbox"
        bash_completion.install "completions/devbox.bash" => "devbox"
        zsh_completion.install "completions/devbox.zsh" => "_devbox"
        fish_completion.install "completions/devbox.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pilat/devbox/releases/download/v0.1.9/devbox_0.1.9_Darwin_arm64.tar.gz"
      sha256 "5b29272a97561e29842963743c816b175a1318c0ea9286b5d7b0bfd6e89b0827"

      def install
        bin.install "devbox"
        bash_completion.install "completions/devbox.bash" => "devbox"
        zsh_completion.install "completions/devbox.zsh" => "_devbox"
        fish_completion.install "completions/devbox.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pilat/devbox/releases/download/v0.1.9/devbox_0.1.9_Linux_x86_64.tar.gz"
        sha256 "c4f12df8e032f6f55e742f36e5253eda6b9d86b211d81b56b81bdcf26c087a06"

        def install
          bin.install "devbox"
          bash_completion.install "completions/devbox.bash" => "devbox"
          zsh_completion.install "completions/devbox.zsh" => "_devbox"
          fish_completion.install "completions/devbox.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pilat/devbox/releases/download/v0.1.9/devbox_0.1.9_Linux_arm64.tar.gz"
        sha256 "ab59f524c0fcaadd0d9bbedd03b533c47d546aaa2e63ecfc9b4685fd36f86a83"

        def install
          bin.install "devbox"
          bash_completion.install "completions/devbox.bash" => "devbox"
          zsh_completion.install "completions/devbox.zsh" => "_devbox"
          fish_completion.install "completions/devbox.fish"
        end
      end
    end
  end
end
